// Code generated by MockGen. DO NOT EDIT.
// Source: ./service/swapi/swapi_service.go

// Package mock_swapi is a generated GoMock package.
package mock_swapi

import (
	reflect "reflect"
	"star-wars/swapi/adapter"

	gomock "github.com/golang/mock/gomock"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetPlanetExternally mocks base method
func (m *MockService) GetPlanetExternally(name string) (adapter.Planets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanetExternally", name)
	ret0, _ := ret[0].(adapter.Planets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanetExternally indicates an expected call of GetPlanetExternally
func (mr *MockServiceMockRecorder) GetPlanetExternally(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanetExternally", reflect.TypeOf((*MockService)(nil).GetPlanetExternally), name)
}
