// Code generated by MockGen. DO NOT EDIT.
// Source: swapi/swapi_service.go

// Package mock_swapi is a generated GoMock package.
package mock_swapi

import (
	gomock "github.com/golang/mock/gomock"
	reflect "reflect"
	adapter "star-wars/swapi/adapter"
)

// MockService is a mock of Service interface
type MockService struct {
	ctrl     *gomock.Controller
	recorder *MockServiceMockRecorder
}

// MockServiceMockRecorder is the mock recorder for MockService
type MockServiceMockRecorder struct {
	mock *MockService
}

// NewMockService creates a new mock instance
func NewMockService(ctrl *gomock.Controller) *MockService {
	mock := &MockService{ctrl: ctrl}
	mock.recorder = &MockServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use
func (m *MockService) EXPECT() *MockServiceMockRecorder {
	return m.recorder
}

// GetPlanet mocks base method
func (m *MockService) GetPlanet(name string) (adapter.Planets, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPlanet", name)
	ret0, _ := ret[0].(adapter.Planets)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPlanet indicates an expected call of GetPlanet
func (mr *MockServiceMockRecorder) GetPlanet(name interface{}) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPlanet", reflect.TypeOf((*MockService)(nil).GetPlanet), name)
}
