FROM golang:1.13.10-alpine AS builder
RUN apk add --update --no-cache \
  build-base \
  upx
WORKDIR /go/src/github.com/star-wars/api/
COPY . .
RUN go build -o import_csv ./importer/cmd/main.go && \
    upx import_csv

FROM alpine:latest AS runtime
WORKDIR /root/
RUN apk --no-cache add ca-certificates && mkdir csv
COPY --from=builder /go/src/github.com/star-wars/api/import_csv ./
CMD ["./import_csv"]
