FROM golang:1.13.10-alpine AS builder
RUN apk add --update --no-cache \
  build-base \ 
  upx
WORKDIR /go/src/github.com/star-wars/api/
COPY . .
RUN touch .env && \
    go build -o web_api ./api/cmd/main.go && \
    upx web_api

FROM alpine:latest AS runtime 
WORKDIR /root/
RUN apk --no-cache add ca-certificates && touch .env
COPY --from=builder /go/src/github.com/star-wars/api/web_api ./
CMD ["./web_api"]
