openapi: 3.0.1
info:
  title: Star Wars
  version: 1.0.0
servers:
- url: http://localhost:8000
tags:
- name: planets
  description: All about the planets
paths:
  /planets:
    get:
      tags:
      - planets
      summary: List all planets
      parameters:
      - name: limit
        in: query
        description: Results limit - Default 3
        required: false
        schema:
          type: string
      - name: skip
        in: query
        description: Skip items - Default 0
        required: false
        schema:
          type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Planets"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInternal"
    post:
      tags:
      - planets
      summary: Add planet
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/PlanetPost"
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Planet'
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInternal"

  /planets/{id}:
    delete:
      tags:
      - planets
      summary: Delete planet
      parameters:
      - name: id
        in: path
        description: Planet ID
        example: "5f2c88567563c4bae600d7e0"
        required: true
        schema:
          type: string
      responses:
        200:
          description: Ok
          content: {}
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInternal"

  /planets/id/{id}:
    get:
      tags:
      - planets
      summary: List planet by id
      parameters:
      - name: id
        in: path
        description: Planet ID
        example: "5f2c88567563c4bae600d7e0"
        required: true
        schema:
          type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Planet"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInternal"

  /planets/name/{name}:
    get:
      tags:
      - planets
      summary: List planet by name
      parameters:
      - name: name
        in: path
        description: Planet Name
        example: "tatooine"
        required: true
        schema:
          type: string
      responses:
        200:
          description: Ok
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/Planet"
        400:
          description: Bad request
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        404:
          description: Not Found
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ErrorRequest'
        500:
          description: Internal Server Error
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/ErrorInternal"
components:
  schemas:
    ErrorRequest:
      type: "object"
      properties:
        error:
          type: "string"
          example: "message"
    ErrorInternal:
      type: "object"
      properties:
        error:
          type: "string"
          example: "internal server error"
    Planets:
      type: array
      items:
        $ref: '#/components/schemas/Planet'
    PlanetPost:
      type: "object"
      properties:
        name:
          type: "string"
          example: "Alderaan"
        climate:
          type: "string"
          example: "temperate"
        terrain:
          type: "string"
          example: "grasslands, mountains"
    Planet:
      type: "object"
      properties:
        id:
          type: "string"
          example: "5f2c88567563c4bae600d7e0"
        name:
          type: "string"
          example: "Alderaan"
        climate:
          type: "string"
          example: "temperate"
        terrain:
          type: "string"
          example: "grasslands, mountains"
        totalFilms:
          type: integer
          example: 5
